sudo: false
language: node_js
node_js:
- '0.8'
- '0.10'
- '0.12'
- '4'
- '6'
- '7'
matrix:
  fast_finish: true
cache:
  directories:
  - "$HOME/.npm"
  - "$HOME/.yarn-cache"
install:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-install.bash)"
before_script:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-verify.bash)"
after_success:
- eval "$(curl -s https://raw.githubusercontent.com/balupton/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  slack:
    secure: db4yn6C91ZJ9d4g3aKKVpcNlOKPXSDDIQausncXgkCmYYH7u82haa+rbixScFXUO4NESUvNTO8YL2/Wr+s5y2vdynqHtcfdVRoA/v67V1Y77Ba8/QIJHbH5xSTbIXA8yZddzczAyy6oMIy9ABj1kyiDNXPma7mUpeMcSVpQwvwk=
  email:
    recipients:
      secure: Xb/79IA2f74uStjtMI5i+6Lq7+l7OAHDvfjX2Z11YkGTNnxDUFAAXXZZS4bhxNEn5FpcW8lZLC/+v0sbNqA0F4LioFV+zL8+fxueqaWLUol7F7cmuyys0ilAuzUJZ0BhIQ8xTh2daDK4h6qXniQak30W7lJxYZ/Kic9fF0gN4e0=
